version: '3.7'

services:
  vsftpd:
    image: phamphu232/vsftpd:20231218
    container_name: con_vsftpd
    ports:
      - '20:20'
      - '21:21'
      - '2222:22'
    volumes:
      - /etc/localtime:/etc/localtime:ro 
      - ./vsftpd.conf:/etc/vsftpd.conf
      - ./volumes/script:/tmp/script
      - ./volumes/home:/home/
    restart: unless-stopped
    working_dir: /home
    command: /tmp/script/start.sh
    #docker run -p 20:20 -p 21:21 -d phamphu232/vsftpd:20231218